import {
  Briefcase,
  DollarSign,
  Factory,
  FileText,
  FolderTree,
  Image as ImageIcon,
  Inbox,
  Mail,
  Newspaper,
  Package,
  Wrench,
} from 'lucide-react';
import type {
  ActivityEntry,
  AdminNotification,
  AdminProduct,
  AdminStatus,
  NavEntry,
  StatusLabel,
} from './types';

export const NAV: NavEntry[] = [
  { group: 'Nội dung' },
  { id: 'banners', label: 'Banner trang chủ', icon: ImageIcon },
  { id: 'categories', label: 'Danh mục', icon: FolderTree },
  { id: 'products', label: 'Sản phẩm', icon: Package },
  { id: 'industries', label: 'Ngành ứng dụng', icon: Factory },
  { id: 'tech', label: 'Vấn đề kỹ thuật', icon: Wrench },
  { id: 'submissions', label: 'Form gửi đến', icon: Inbox, hot: true },
  { id: 'news', label: 'Tin tức', icon: Newspaper },
  // { id: "recruitment",   label: "Tuyển dụng",       icon: Briefcase,  count: 6 },
];

export const NOTIFICATIONS: AdminNotification[] = [
  {
    id: 1,
    type: 'quote',
    icon: DollarSign,
    title: 'Yêu cầu báo giá mới — Cty Sơn Nippon VN',
    sub: 'AGITAN® 120 (200kg) + EDAPLAN® 470 (50kg)',
    time: '2 phút trước',
    unread: true,
    target: { page: 'submissions', id: 'SUB-2026-0429-001' },
  },
  {
    id: 2,
    type: 'tech',
    icon: Wrench,
    title: 'Tư vấn kỹ thuật — Anh Tuấn (Đại Bàng Paint)',
    sub: 'Vấn đề bọt khí trên mực in flexo gốc nước',
    time: '12 phút trước',
    unread: true,
    target: { page: 'submissions', id: 'SUB-2026-0429-002' },
  },
  {
    id: 3,
    type: 'cv',
    icon: FileText,
    title: 'CV ứng tuyển — Lab Engineer',
    sub: 'Nguyễn Thanh Hà — 3 năm KN MÜNZING',
    time: '28 phút trước',
    unread: true,
    target: { page: 'recruitment', id: 1 },
  },
  {
    id: 4,
    type: 'contact',
    icon: Mail,
    title: 'Liên hệ chung — JR Industrial',
    sub: 'Yêu cầu mẫu thử HYDROPALAT® WE 3475',
    time: '1 giờ trước',
    unread: true,
    target: { page: 'submissions', id: 'SUB-2026-0429-004' },
  },
  {
    id: 5,
    type: 'quote',
    icon: DollarSign,
    title: 'Yêu cầu báo giá — Vinaplast',
    sub: '5 mã wax additive cho masterbatch PE',
    time: '2 giờ trước',
    unread: false,
    target: { page: 'submissions', id: 'SUB-2026-0429-005' },
  },
  {
    id: 6,
    type: 'tech',
    icon: Wrench,
    title: 'Tư vấn kỹ thuật — Cty Sơn 4 Oranges',
    sub: 'Tối ưu công thức sơn xây dựng',
    time: '3 giờ trước',
    unread: false,
    target: { page: 'submissions', id: 'SUB-2026-0428-021' },
  },
  {
    id: 7,
    type: 'cv',
    icon: FileText,
    title: 'CV ứng tuyển — Tech Sales miền Bắc',
    sub: 'Trần Minh Quân',
    time: '5 giờ trước',
    unread: false,
    target: { page: 'recruitment', id: 3 },
  },
  {
    id: 8,
    type: 'quote',
    icon: DollarSign,
    title: 'Báo giá đã được Sales tiếp nhận',
    sub: "ĐH#2026-0428-12 chuyển sang trạng thái 'Đang xử lý'",
    time: 'Hôm qua',
    unread: false,
    target: { page: 'submissions', id: 'SUB-2026-0428-019' },
  },
];

export const ACTIVITY: ActivityEntry[] = [
  {
    who: 'Bạn',
    what: 'đã cập nhật sản phẩm',
    target: 'AGITAN® 120',
    time: '10 phút trước',
  },
  {
    who: 'Sales 1',
    what: 'đã xử lý yêu cầu báo giá',
    target: 'ĐH#2026-0428-12',
    time: '1 giờ trước',
  },
  {
    who: 'Tech 1',
    what: 'đã trả lời tư vấn kỹ thuật',
    target: '4 Oranges',
    time: '2 giờ trước',
  },
  {
    who: 'Content',
    what: 'đã đăng bài viết mới',
    target: '5 lưu ý chọn defoamer cho sơn nước',
    time: '3 giờ trước',
  },
  {
    who: 'HR',
    what: 'đã thêm vị trí tuyển dụng',
    target: 'Lab Engineer',
    time: 'Hôm qua',
  },
  {
    who: 'Super Admin',
    what: 'đã cập nhật banner',
    target: 'AGITAN® thế hệ mới',
    time: 'Hôm qua',
  },
];

export const STATUS_LABELS: Record<AdminStatus, StatusLabel> = {
  new: { lbl: 'Mới', cls: 'pill--brand' },
  'in-progress': { lbl: 'Đang xử lý', cls: 'pill--info' },
  done: { lbl: 'Đã xử lý', cls: 'pill--success' },
  active: { lbl: 'Đang chạy', cls: 'pill--success' },
  scheduled: { lbl: 'Đã lên lịch', cls: 'pill--info' },
  expired: { lbl: 'Hết hạn', cls: 'pill--neutral' },
  disabled: { lbl: 'Tắt', cls: 'pill--neutral' },
  published: { lbl: 'Đã xuất bản', cls: 'pill--success' },
  draft: { lbl: 'Nháp', cls: 'pill--neutral' },
};
